//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ISSUE
    {
        
        public int ISSUE_ID { get; set; }
        [Required]
        public Nullable<int> REQUEST_ID { get; set; }
        [Required]
        public System.DateTime ISSUE_DATE { get; set; }
        [Required]
        public System.DateTime RETURN_DATE { get; set; }
        public Nullable<float> FINE { get; set; }
        public int REISSUED { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
